BEPs redirect cleanup
bids-standard/bids-website pull request #399
Opened 2024-05-20 00:30 UTC by iamdamion

- Cleaned up BEPs links to not redirect.
- Made all external links in new tab.
- Adjusted beps table jinja file to take link from yaml file

2024-05-28 13:01 UTC, Remi-Gau commented on data/beps.yml
> +    link: https://docs.google.com/document/d/1pWCb02YNv5W-UZZja24fZrdXLm4X7knXMiZI7E2z7mY/
I believe there is a PR for this now

2024-05-28 13:01 UTC, Remi-Gau commented on data/beps.yml
> +    link: https://docs.google.com/document/d/1NT1ERdL41oz3NibIFRyVQ2iR8xH-dKY-lRCB4eyVeRo/
I believe there is a PR for this on but am not 100% sure

2024-05-28 13:02 UTC, Remi-Gau commented on data/beps_completed.yml
> +    link: https://github.com/bids-bep001/bids-specification
probably better to point to the relevant appendix section of the spec website

2024-05-28 13:03 UTC, Remi-Gau commented on data/beps_completed.yml
> +    link: https://docs.google.com/document/d/1bq5eNDHTb6Nkx3WUiOBgKvLNnaa5OMcGtD0AZ9yms2M/
probably better to point to URL of the current bids stats model website

this website will ultimately move when we merge all our website but let's start with valid URL for now

2024-05-28 13:04 UTC, Remi-Gau commented on data/beps_completed.yml
> +    link: https://github.com/bids-standard/bids-specification/pull/265
probably best to point to the relevant derivtives section of the specification

2024-05-28 13:05 UTC, Remi-Gau commented on data/beps_completed.yml
> +    link: https://docs.google.com/document/d/15tnn5F10KpgHypaQJNNGiNKsni9035GtDqJzWqkkP6c/
link to the ASL section in the spec

2024-05-28 13:05 UTC, Remi-Gau commented on data/beps_completed.yml
> +    link: https://docs.google.com/document/d/1ArMZ9Y_quTKXC-jNXZksnedK2VHHoKP3HCeO5HPcgLE/
link to the EEG section in the spec

2024-05-28 13:05 UTC, Remi-Gau commented on data/beps_completed.yml
> +    link: https://docs.google.com/document/d/1gs7USIVO1OApZs3IVo6TeXw9_tfzxhjM2-m--ex4g6o/
link to the HED section in the spec

2024-05-28 13:05 UTC, Remi-Gau commented on data/beps_completed.yml
> +    link: https://docs.google.com/document/d/1FWex_kSPWVh_f4rKgd5rxJmxlboAPtQlmBc1gyZlRZM/
link to the MEG section in the spec

2024-05-28 13:05 UTC, Remi-Gau commented on data/beps_completed.yml
> +    link: https://github.com/bids-standard/bids-specification/pull/633
link to the PET section in the spec

2024-05-28 13:05 UTC, Remi-Gau commented on data/beps_completed.yml
> +    link: https://docs.google.com/document/d/1qMUkoaXzRMlJuOcfTYNr3fTsrl4SewWjffjMD5Ew6GY/
link to the iEEG section in the spec

2024-05-28 13:06 UTC, Remi-Gau commented on data/beps_completed.yml
> +    link: https://docs.google.com/document/d/1uRkgyzESLKuGjXi98Z97Wh6vt-iLN5nOAb9TG16CjUs/
link to the genetics section in the spec

2024-05-28 13:06 UTC, Remi-Gau commented on data/beps_completed.yml
> +    link: https://docs.google.com/document/d/104HLZedFtx0TaXEUwd7eyWvJUlc0CcSUtCzwjNgmGxE/
link to the bids-execution website

this one too will be merged with the rest but once again let's use valid URLs for now

2024-05-28 13:07 UTC, Remi-Gau commented on data/beps_completed.yml
> +    link: https://docs.google.com/document/d/1iaaLKgWjK5pcISD1MVxHKexB3PZWfE2aAC5HF_pCZWo/
link to motion part of the spec

2024-05-28 13:07 UTC, Remi-Gau commented on data/beps_completed.yml
> +    link: https://docs.google.com/document/d/1FzPt7TVpIAtlhrF9_9b2VBCZOrRXJASEMyHndhDQKl8/
link to NIRS seection of the spec

2024-05-28 13:07 UTC, Remi-Gau commented on data/beps_completed.yml
> +    link: https://docs.google.com/document/d/1Nlu6QVQrbOQtdtcRarsONbX5SrOubXWBvkV37LRRqrc/
link to microscopy section of the spec

2024-05-28 13:08 UTC, Remi-Gau requested changes
mostly needs changing the links of the merged BEPs to point to either real websites or the relevant section of the spec

2024-05-29 20:09 UTC, iamdamion commented
updated links according to notes above

2024-05-30 08:04 UTC, Remi-Gau approved these changes
Awesome! Thanks!

2024-05-30 08:04 UTC, merged