[ENH] added md files from bids-starter-kit repository
bids-standard/bids-website pull request #465
Opened 2024-07-30 20:25 UTC by robertoostenveld

I believe that all menu items under "Getting started" in the new navigation now have their corresponding page.

2024-07-30 20:26 UTC, robertoostenveld commented
@Remi-Gau can you review and merge in the `enh/new_nav` branch that you have created?

2024-07-31 11:06 UTC, Remi-Gau commented on docs/collaboration/code_of_conduct.md
right now we are using the code of conduct of the spec: we have an issue (and a future working group) to uniformize our code of conduct across repos.

for this reason I would not move the code of conduct in the website.

2024-07-31 11:12 UTC, Remi-Gau requested changes

2024-07-31 11:12 UTC, Remi-Gau commented on docs/collaboration/code_of_conduct.md
right now we are using the code of conduct of the spec: we have an issue (and a future working group) to uniformize our code of conduct across repos.

for this reason I would not move the code of conduct in the website.

2024-07-31 11:12 UTC, Remi-Gau commented on docs/getting_started/src
Can you open a PR on the `bfm` branch of the starter kit to explain where each page has been moved ?

See for example:
https://github.com/bids-standard/bids-starter-kit/blob/bfm/src/glossary.md?plain=1

2024-07-31 11:12 UTC, Remi-Gau commented
I can take care of those changes if you want Robert.

2024-07-31 12:26 UTC, Remi-Gau commented
will push additional commits on this branch

2024-07-31 12:39 UTC, Remi-Gau approved these changes

2024-07-31 12:59 UTC, Remi-Gau commented
will fix links later

2024-07-31 12:59 UTC, merged